remote_theme: just-the-docs/just-the-docs

logo: "/assets/probable-futures-logo-long.svg"


# Example of other things you can add here: https://github.com/just-the-docs/just-the-docs/blob/main/_config.yml
