
title: Probable Futures Developer Documentation
logo: "/assets/probable-futures-logo-long.svg"

remote_theme: just-the-docs/just-the-docs
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://probable-futures.github.io" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty

exclude:
 # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# footer_content: "This work is licensed under a Creative Commons Attribution 4.0 International License. <a href=\"https://probablefutures.org/licensing/\">Read more about Probable Futures licensing.</a>"


# Example of other things you can add here: https://github.com/just-the-docs/just-the-docs/blob/main/_config.yml
